### ISSUE TITLE
i like this idea

### ISSUE THREAD

**Issue by feitian124** [open-company/home#1]
software project is about dealing with complexity. 

If we find proper way to `divide` the complexity into small `pieces` so each member can finish them quickly and easy, then it is very likely that the project have a happy ending. But the `divide` is not easy,  the pieces should work well itself and also cooperate with each other; they'd better have no dependent with each other etc. .

the reason why open source is good is that the members do the `pieces` by interesting and the `pieces` is small enough. but this model has its own weakness, for example, it usually slow so needs years to became mature.

there has been some idea to improve the speed, [bountysource.com -- Accelerate open-source development with our community] (https://www.bountysource.com). 

i think the key is to find a way to `divide-finish-pay`, opensource or not is not the key, hope OC can do more and better in the similar way.

**Comment by open-company** [comment]
Yes, you are right.

The life cycle of OCOSP is recursive more than linear.
The "divide" is a background job which is processed by daemon OC.

Since the OC also play as a banker, the developers is the real boss.
The boss manage project during the entire life cycle, when boss need some money, they run a process to get money from bank.
The manage tasks includ develop, test, documentation, support and upgrade.

I think I should write more details about this into doc.
Maybe a diagram will got more expressive.
